### ISSUE TITLE
Installation error after fresh debian installation

### ISSUE THREAD

**Issue by pic0** [mistio/mist.io#391] opened 2015-02-27 15:32 UTC
Hi together,

i've just installing mist.io in order of the documentation after an fresh installation of debian 7.8. 
I don't get, why these error occurs
```
root@pro:/usr/src/mist.io# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
```

```
root@pro:/usr/src/mist.io# ./bin/buildout -v
Installing 'mr.developer'.
We have no distributions for mr.developer that satisfies 'mr.developer'.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 467, in install
    self._load_extensions()
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 995, in _load_extensions
    newest=self.newest, allow_hosts=self._allow_hosts)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 420, in _obtain
    if _final_version(dist.parsed_version)
  File "/usr/src/mist.io/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 1408, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease'
```

**Comment by mgogoulos** [comment] 2015-02-27 15:51
Hello, 

I have just confirmed what you report. Let me have a look and I will come back as soon as I have a solution, thanks

**Comment by mgogoulos** [comment] 2015-02-27 16:03
Ok here's a quick solution, until we update bootstrap.py:

```
./bin/pip install setuptools --upgrade
```
then run bootstrap.py again
```
./bin/python bootstrap.py
```
then run buildout
```
./bin/buildout -v
```
and you should be ok

**Comment by mgogoulos** [comment] 2015-02-27 16:19
Since I see you are running buildout as root, mist.io does not need to be run as root (in fact celery and memcache will not start without tunning,  as root).

So please create a user and run the buildout as this user! 

Cheers

**Comment by mgogoulos** [comment] 2015-03-02 13:53
This has been solved and will be merged to the master branch in a few hours. If you have other issues please let us know!

**Closed by mgogoulos** 2015-03-02 13:53 UTC

**Comment by comihai** [comment] 2015-04-01 06:27
Hi,

I have a problem in the same way

<addr> mihai@mihai-PC:~/bob/bob.spear-1.1.2$ ./bin/buildout -v
/usr/lib/python2.6/dist-packages/setuptools/package_index.py:156: UserWarning: Unbuilt egg for setuptools [unknown version] (/home/mihai/bob/bob.spear-1.1.2/bin)
  Environment.__init__(self,*args,**kw)
Installing 'zc.buildout', 'setuptools'.
While:
  Installing.
  Checking for upgrades.
  Getting distribution for 'zc.buildout>=2.3.1'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 475, in install
    self._maybe_upgrade()
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 910, in _maybe_upgrade
    allow_hosts = self._allow_hosts
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 253, in _satisfied
    if _final_version(dist.parsed_version)
  File "/home/mihai/bob/bob.spear-1.1.2/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 1408, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease'
 <addr>


i tried to run the commands above in the bin directory but I have no file or directory called pip. I know that pip is a package management system used to install and manage software written in python but i cannot handle it. I need some directions in this way if possible.

**Comment by mgogoulos** [comment] 2015-04-01 11:10
Hi,
it is highly advised that you follow directions on https://github.com/mistio/mist.io/ and install it using a virtualenv. Virtualenv is a tool to create isolated Python environments, and it will install pip (package management) as well on your virtualenv.

```
sudo aptitude install python-virtualenv
```
then 
```
git clone https://github.com/mistio/mist.io.git
cd mist.io
virtualenv --no-site-packages .
./bin/pip install ansible
./bin/python bootstrap.py
./bin/buildout -v
```

Try the above and let us know if it works for you

**Comment by comihai** [comment] 2015-04-01 14:32
Hi,

After running the last comand `./bin/buildout -v` i got an error 

`Installing cloudpy.
Installing 'ipython', 'Pillow', 'mist.io', 'PasteScript'.
We have no distributions for ipython that satisfies 'ipython'.
Getting distribution for 'ipython'.
Running easy_install:
"/home/mihai/mist.io/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mihai/mist.io/eggs/tmpsvcLMi" "-q" "/tmp/tmpDIpzk7get_dist/ipython-3.0.0.zip"
path=/home/mihai/mist.io/lib/python2.6/site-packages

ERROR: IPython requires Python version 2.7 or 3.3 or above.
error: Setup script exited with 1
An error occurred when trying to install ipython 3.0.0. Look above this message for any errors that were output by easy_install.
While:
  Installing cloudpy.
  Getting distribution for 'ipython'.
Error: Couldn't install: ipython 3.0.0
`
This is a part of the log.
I install python2.7 but error persists.

**Comment by comihai** [comment] 2015-04-01 17:52
My goal is to install a tool for speaker recognition 
I followed this tutorial to install bob.spear https://pypi.python.org/pypi/bob.spear but 
i encountered a problem described in the first comment, at this command `$ ./bin/buildout`

**Comment by mgogoulos** [comment] 2015-04-01 20:58
hi, 
please check the instructions on https://github.com/mistio/mist.io/
Mist.io is tested and developed in python 2.7, so you'd better use it instead of python 2.6

There's also a mention related to python 2.6

"If you are using Python 2.6 you'll have to install ipython version 1, otherwise buildout will fail"
```
    ./bin/pip install ipython==1 
```

**Comment by comihai** [comment] 2015-04-02 05:42
I followed exactly the instructions `https://github.com/mistio/mist.io/` but I came again over the previous error

mihai@mihai-PC:~/mist.io$ ./bin/buildout -v
Installing 'mr.developer'.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 467, in install
    self._load_extensions()
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/buildout.py", line 995, in _load_extensions
    newest=self.newest, allow_hosts=self._allow_hosts)
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 253, in _satisfied
    if _final_version(dist.parsed_version)
  File "/home/mihai/mist.io/eggs/zc.buildout-2.3.1-py2.6.egg/zc/buildout/easy_install.py", line 1408, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease'

**Comment by comihai** [comment] 2015-04-02 13:55
Sorry for my misunderstanding ... i'm a newbie 
1)
I use a virtual machine.
`mihai@mihai-PC:~/mist.io$ cat /etc/*-release`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=10.04
DISTRIB_CODENAME=lucid
DISTRIB_DESCRIPTION="Ubuntu 10.04.4 LTS"

2)
`mihai@mihai-PC:~/mist.io$ ./bin/pip install setuptools --upgrade`
Requirement already up-to-date: setuptools in ./lib/python2.6/site-packages

`mihai@mihai-PC:~/mist.io$ git  pull`
Already up-to-date.

3)
`mihai@mihai-PC:~/mist.io$ virtualenv -p python2.7 . `
Already using interpreter /usr/local/bin/python2.7
New python executable in ./bin/python2.7
Not overwriting existing python script ./bin/python (you must use ./bin/python2.7)
Installing setuptools, pip...done.

**Comment by mgogoulos** [comment] 2015-04-02 14:14
Hi, 
mmm this is a very old version of Ubuntu! You should try on a more recent Ubuntu OS (eg 14.04) :)

**Comment by comihai** [comment] 2015-04-03 09:17
I created a virtual machine with Ubuntu 14.04. I successfully installed mist.io.
I tried to install bob.spear but i came across an error again

mihai@mihai-PC:~/bob.spear-1.1.2$ ./bin/buildout -v
Develop: '/home/mihai/bob.spear-1.1.2/.'
Installing 'xbob.buildout'.
We have no distributions for xbob.buildout that satisfies 'xbob.buildout'.
Getting distribution for 'xbob.buildout'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mihai/bob.spear-1.1.2/eggs/tmpr3GXkY" "-q" "/tmp/tmparGOWhget_dist/xbob.buildout-1.0.3.zip"
path=/usr/local/lib/python2.7/dist-packages

Got xbob.buildout 1.0.3.
Picked: xbob.buildout = 1.0.3
Getting required 'zc.recipe.egg>=2.0.0a3'
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mihai/bob.spear-1.1.2/eggs/tmpDmcIVz" "-q" "/tmp/tmpk2rn7pget_dist/zc.recipe.egg-2.0.1.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

Got zc.recipe.egg 2.0.1.
Picked: zc.recipe.egg = 2.0.1
Installing scripts.
Installing 'bob>=1.2.0'.
We have no distributions for bob that satisfies 'bob>=1.2.0'.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.

**Comment by comihai** [comment] 2015-04-03 10:06
I also download another bootstrap-buildout.py because when i was running the command `$ python bootstrap-buildout.py` the bin/buildout file was not  created. I tried this from here https://github.com/bioidiap/spear/issues/7

Sorry for my bad english.

**Comment by mgogoulos** [comment] 2015-04-03 10:11
Hi comihai, 

we don't support other projects, including bob.spear and bioidiap that you mention. We can only provide support for mist.io project. You should contact the other projects for assistance!

**Comment by janubhandari** [comment] 2015-09-10 11:28
hi after running the buildout iam gettin the following error 


Error downloading extends for URL http://projects.unbit.it/downloads/uwsgi-2.0.5.1.tar.gz: HTTP Error 403: Forbidden

**Comment by janubhandari** [comment] 2015-09-10 11:36
Hi after running the following command 

./bin/buildout -v




I am getting the following Error in Ubuntu OS


Error downloading extends for URL http://projects.unbit.it/downloads/uwsgi-2.0.5.1.tar.gz: HTTP Error 403: Forbidden


Thanks in advance :)

**Comment by mgogoulos** [comment] 2015-09-10 14:49
Hi, 

check that you can wget this file, the link opens for me. Maybe there has been a restart on that server, or some network issue, try to re-run the buildout if the link opens for you

Regards
